### ISSUE TITLE
Conversion from [c32] to i32 not possible, to undefined

### ISSUE THREAD

**Issue by TheNawaKer** [GNU-Ymir/yruntime#6]
When converting a [c32] to an i32 with the function to, Gyc returns the following error:
`Error : the call operator is not defined for type std::conv::to(i32)::to and {[c32]}`

Example:

```
import std::conv;
import std::io;

def main(){
  let res = "10";
  let convert = res.to!i32();
  println(convert);
}
```

**Comment by EmileCadorel** [comment]
Conversion from [c32] and [c8], to i32 and u32 is now possible.
The test : [main.yr](https://github.com/GNU-Ymir/Ymir-Test/blob/master/conv/2/main.yr)

The functions to are defined for every `iX`, `uX` types, except (`usize` and `isize`)
And hexadecimal conversion only produces `uX` values.
